# Generated by Django 4.2.4 on 2023-09-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name_plural": "Message"},
        ),
        migrations.RemoveField(
            model_name="message",
            name="username",
        ),
        migrations.AddField(
            model_name="message",
            name="message_body",
            field=models.TextField(default="trs"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="receiving_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiving_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sending_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sending_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
